# Generated by Django 4.2.3 on 2023-07-26 00:51

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('checkout_id', models.CharField(max_length=500)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.order')),
            ],
        ),
    ]
