# Generated by Django 4.2.3 on 2023-07-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_authors_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='publishers',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='IntegerRating',
            new_name='integerRating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='TextRating',
            new_name='textRating',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
