# Generated by Django 4.2.3 on 2023-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_publication_date_book_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='social_twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
